// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8PwgGRpqC1sfX2e6Md5Z7h
// Component: xi8_zROhSrDY

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 8PwgGRpqC1sfX2e6Md5Z7h/projectcss
import sty from "./PlasmicNavBarToggleBars.module.css"; // plasmic-import: xi8_zROhSrDY/css

createPlasmicElementProxy;

export type PlasmicNavBarToggleBars__VariantMembers = {
  closeState: "closeState";
};
export type PlasmicNavBarToggleBars__VariantsArgs = {
  closeState?: SingleBooleanChoiceArg<"closeState">;
};
type VariantPropType = keyof PlasmicNavBarToggleBars__VariantsArgs;
export const PlasmicNavBarToggleBars__VariantProps = new Array<VariantPropType>(
  "closeState"
);

export type PlasmicNavBarToggleBars__ArgsType = {};
type ArgPropType = keyof PlasmicNavBarToggleBars__ArgsType;
export const PlasmicNavBarToggleBars__ArgProps = new Array<ArgPropType>();

export type PlasmicNavBarToggleBars__OverridesType = {
  root?: Flex__<"div">;
  barGreen?: Flex__<"div">;
  barMid?: Flex__<"div">;
  barBot?: Flex__<"div">;
};

export interface DefaultNavBarToggleBarsProps {
  closeState?: SingleBooleanChoiceArg<"closeState">;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicNavBarToggleBars__RenderFunc(props: {
  variants: PlasmicNavBarToggleBars__VariantsArgs;
  args: PlasmicNavBarToggleBars__ArgsType;
  overrides: PlasmicNavBarToggleBars__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "closeSymbol",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false
      },
      {
        path: "closeState",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.closeState
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  return (
    <Stack__
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.root,
        { [sty.rootcloseState]: hasVariant($state, "closeState", "closeState") }
      )}
    >
      <div
        data-plasmic-name={"barGreen"}
        data-plasmic-override={overrides.barGreen}
        className={classNames(projectcss.all, sty.barGreen, {
          [sty.barGreencloseState]: hasVariant(
            $state,
            "closeState",
            "closeState"
          )
        })}
      />

      <div
        data-plasmic-name={"barMid"}
        data-plasmic-override={overrides.barMid}
        className={classNames(projectcss.all, sty.barMid, {
          [sty.barMidcloseState]: hasVariant($state, "closeState", "closeState")
        })}
      />

      <div
        data-plasmic-name={"barBot"}
        data-plasmic-override={overrides.barBot}
        className={classNames(projectcss.all, sty.barBot, {
          [sty.barBotcloseState]: hasVariant($state, "closeState", "closeState")
        })}
      />
    </Stack__>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "barGreen", "barMid", "barBot"],
  barGreen: ["barGreen"],
  barMid: ["barMid"],
  barBot: ["barBot"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  barGreen: "div";
  barMid: "div";
  barBot: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNavBarToggleBars__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNavBarToggleBars__VariantsArgs;
    args?: PlasmicNavBarToggleBars__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicNavBarToggleBars__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicNavBarToggleBars__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicNavBarToggleBars__ArgProps,
          internalVariantPropNames: PlasmicNavBarToggleBars__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicNavBarToggleBars__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNavBarToggleBars";
  } else {
    func.displayName = `PlasmicNavBarToggleBars.${nodeName}`;
  }
  return func;
}

export const PlasmicNavBarToggleBars = Object.assign(
  // Top-level PlasmicNavBarToggleBars renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    barGreen: makeNodeComponent("barGreen"),
    barMid: makeNodeComponent("barMid"),
    barBot: makeNodeComponent("barBot"),

    // Metadata about props expected for PlasmicNavBarToggleBars
    internalVariantProps: PlasmicNavBarToggleBars__VariantProps,
    internalArgProps: PlasmicNavBarToggleBars__ArgProps
  }
);

export default PlasmicNavBarToggleBars;
/* prettier-ignore-end */
