// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8PwgGRpqC1sfX2e6Md5Z7h
// Component: iQLRvMo3zErj

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 8PwgGRpqC1sfX2e6Md5Z7h/projectcss
import sty from "./PlasmicVSpacing.module.css"; // plasmic-import: iQLRvMo3zErj/css

createPlasmicElementProxy;

export type PlasmicVSpacing__VariantMembers = {
  vSpacing:
    | "v01252"
    | "v0254"
    | "v058"
    | "v116"
    | "v232"
    | "v348"
    | "v464"
    | "v580"
    | "v696"
    | "v8128"
    | "v12192";
};
export type PlasmicVSpacing__VariantsArgs = {
  vSpacing?: SingleChoiceArg<
    | "v01252"
    | "v0254"
    | "v058"
    | "v116"
    | "v232"
    | "v348"
    | "v464"
    | "v580"
    | "v696"
    | "v8128"
    | "v12192"
  >;
};
type VariantPropType = keyof PlasmicVSpacing__VariantsArgs;
export const PlasmicVSpacing__VariantProps = new Array<VariantPropType>(
  "vSpacing"
);

export type PlasmicVSpacing__ArgsType = {};
type ArgPropType = keyof PlasmicVSpacing__ArgsType;
export const PlasmicVSpacing__ArgProps = new Array<ArgPropType>();

export type PlasmicVSpacing__OverridesType = {
  root?: Flex__<"div">;
};

export interface DefaultVSpacingProps {
  vSpacing?: SingleChoiceArg<
    | "v01252"
    | "v0254"
    | "v058"
    | "v116"
    | "v232"
    | "v348"
    | "v464"
    | "v580"
    | "v696"
    | "v8128"
    | "v12192"
  >;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicVSpacing__RenderFunc(props: {
  variants: PlasmicVSpacing__VariantsArgs;
  args: PlasmicVSpacing__ArgsType;
  overrides: PlasmicVSpacing__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "vSpacing",
        type: "private",
        variableType: "variant",
        initFunc: ({ $props, $state, $queries, $ctx }) => $props.vSpacing
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        plasmic_plasmic_rich_components_css.plasmic_tokens,
        sty.root,
        {
          [sty.rootvSpacing_v01252]: hasVariant($state, "vSpacing", "v01252"),
          [sty.rootvSpacing_v0254]: hasVariant($state, "vSpacing", "v0254"),
          [sty.rootvSpacing_v058]: hasVariant($state, "vSpacing", "v058"),
          [sty.rootvSpacing_v116]: hasVariant($state, "vSpacing", "v116"),
          [sty.rootvSpacing_v12192]: hasVariant($state, "vSpacing", "v12192"),
          [sty.rootvSpacing_v232]: hasVariant($state, "vSpacing", "v232"),
          [sty.rootvSpacing_v348]: hasVariant($state, "vSpacing", "v348"),
          [sty.rootvSpacing_v464]: hasVariant($state, "vSpacing", "v464"),
          [sty.rootvSpacing_v580]: hasVariant($state, "vSpacing", "v580"),
          [sty.rootvSpacing_v696]: hasVariant($state, "vSpacing", "v696"),
          [sty.rootvSpacing_v8128]: hasVariant($state, "vSpacing", "v8128")
        }
      )}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicVSpacing__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicVSpacing__VariantsArgs;
    args?: PlasmicVSpacing__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicVSpacing__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicVSpacing__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicVSpacing__ArgProps,
          internalVariantPropNames: PlasmicVSpacing__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicVSpacing__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicVSpacing";
  } else {
    func.displayName = `PlasmicVSpacing.${nodeName}`;
  }
  return func;
}

export const PlasmicVSpacing = Object.assign(
  // Top-level PlasmicVSpacing renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicVSpacing
    internalVariantProps: PlasmicVSpacing__VariantProps,
    internalArgProps: PlasmicVSpacing__ArgProps
  }
);

export default PlasmicVSpacing;
/* prettier-ignore-end */
