// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8PwgGRpqC1sfX2e6Md5Z7h
// Component: JoUwNDKCzHcX

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { NavigationBar } from "@plasmicpkgs/plasmic-nav";
import Button2 from "../../Button2"; // plasmic-import: UFQeZdp76e18/component
import { Embed } from "@plasmicpkgs/plasmic-basic-components";

import { useScreenVariants as useScreenVariantsikbnv5YY9ZVd } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: ikbnv5yY9zVD/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 8PwgGRpqC1sfX2e6Md5Z7h/projectcss
import sty from "./PlasmicFormulaireDeCommande.module.css"; // plasmic-import: JoUwNDKCzHcX/css

import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: ftHUtpQxxIrf/icon
import Icon38Icon from "./icons/PlasmicIcon__Icon38"; // plasmic-import: sl6S8_6N7zOW/icon

createPlasmicElementProxy;

export type PlasmicFormulaireDeCommande__VariantMembers = {};
export type PlasmicFormulaireDeCommande__VariantsArgs = {};
type VariantPropType = keyof PlasmicFormulaireDeCommande__VariantsArgs;
export const PlasmicFormulaireDeCommande__VariantProps =
  new Array<VariantPropType>();

export type PlasmicFormulaireDeCommande__ArgsType = {};
type ArgPropType = keyof PlasmicFormulaireDeCommande__ArgsType;
export const PlasmicFormulaireDeCommande__ArgProps = new Array<ArgPropType>();

export type PlasmicFormulaireDeCommande__OverridesType = {
  formulaireDeCommande?: Flex__<"div">;
  navigationBar?: Flex__<typeof NavigationBar>;
  h1?: Flex__<"h1">;
  embedHtml?: Flex__<typeof Embed>;
};

export interface DefaultFormulaireDeCommandeProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicFormulaireDeCommande__RenderFunc(props: {
  variants: PlasmicFormulaireDeCommande__VariantsArgs;
  args: PlasmicFormulaireDeCommande__ArgsType;
  overrides: PlasmicFormulaireDeCommande__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsikbnv5YY9ZVd()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />
        <title key="title">
          {PlasmicFormulaireDeCommande.pageMetadata.title}
        </title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicFormulaireDeCommande.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicFormulaireDeCommande.pageMetadata.title}
        />
        <meta
          key="description"
          name="description"
          content={PlasmicFormulaireDeCommande.pageMetadata.description}
        />
        <meta
          key="og:description"
          property="og:description"
          content={PlasmicFormulaireDeCommande.pageMetadata.description}
        />
        <meta
          key="twitter:description"
          name="twitter:description"
          content={PlasmicFormulaireDeCommande.pageMetadata.description}
        />
        <meta
          key="og:image"
          property="og:image"
          content={PlasmicFormulaireDeCommande.pageMetadata.ogImageSrc}
        />
        <meta
          key="twitter:image"
          name="twitter:image"
          content={PlasmicFormulaireDeCommande.pageMetadata.ogImageSrc}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"formulaireDeCommande"}
          data-plasmic-override={overrides.formulaireDeCommande}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.formulaireDeCommande
          )}
        >
          {(
            hasVariant(globalVariants, "screen", "bigScreen") ? true : false
          ) ? (
            <NavigationBar
              data-plasmic-name={"navigationBar"}
              data-plasmic-override={overrides.navigationBar}
              brand={
                (
                  hasVariant(globalVariants, "screen", "desktop")
                    ? true
                    : hasVariant(globalVariants, "screen", "bigScreen")
                    ? true
                    : false
                ) ? (
                  <Button2
                    className={classNames("__wab_instance", sty.button2__mp7Gz)}
                    color={"link"}
                    endIcon={
                      <Icon38Icon
                        className={classNames(projectcss.all, sty.svg__wRy3Y)}
                        role={"img"}
                      />
                    }
                    link={`/`}
                    size={"minimal"}
                    startIcon={
                      <CheckSvgIcon
                        className={classNames(projectcss.all, sty.svg___7UnvC)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__l4DaF
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 600 }}
                        >
                          {"Cloven"}
                        </span>
                      </React.Fragment>
                    </div>
                  </Button2>
                ) : null
              }
              className={classNames("__wab_instance", sty.navigationBar)}
              closeButton={
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__f9VO)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  src={"https://static1.plasmic.app/close.svg"}
                />
              }
              itemsGap={8}
              menuItems={
                <React.Fragment>
                  {(
                    hasVariant(globalVariants, "screen", "desktop")
                      ? true
                      : hasVariant(globalVariants, "screen", "bigScreen")
                      ? true
                      : false
                  ) ? (
                    <Button2
                      className={classNames(
                        "__wab_instance",
                        sty.button2__eKrxi
                      )}
                      color={"link"}
                      endIcon={
                        <Icon38Icon
                          className={classNames(projectcss.all, sty.svg__e8Jzp)}
                          role={"img"}
                        />
                      }
                      link={`/catalogue`}
                      size={"minimal"}
                      startIcon={
                        <CheckSvgIcon
                          className={classNames(projectcss.all, sty.svg___2YsJ)}
                          role={"img"}
                        />
                      }
                      submitsForm={true}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__oOuMw
                        )}
                      >
                        {"COLLECTION"}
                      </div>
                    </Button2>
                  ) : null}
                  {(
                    hasVariant(globalVariants, "screen", "desktop")
                      ? true
                      : hasVariant(globalVariants, "screen", "bigScreen")
                      ? true
                      : false
                  ) ? (
                    <Button2
                      className={classNames(
                        "__wab_instance",
                        sty.button2__nYlds
                      )}
                      color={"link"}
                      endIcon={
                        <Icon38Icon
                          className={classNames(projectcss.all, sty.svg__xrvnb)}
                          role={"img"}
                        />
                      }
                      link={`/a-propos`}
                      size={"minimal"}
                      startIcon={
                        <CheckSvgIcon
                          className={classNames(projectcss.all, sty.svg__uh7Ia)}
                          role={"img"}
                        />
                      }
                      submitsForm={true}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__xvBU
                        )}
                      >
                        {"\u00c0 PROPOS"}
                      </div>
                    </Button2>
                  ) : null}
                  {(
                    hasVariant(globalVariants, "screen", "desktop")
                      ? true
                      : hasVariant(globalVariants, "screen", "bigScreen")
                      ? true
                      : false
                  ) ? (
                    <Button2
                      className={classNames(
                        "__wab_instance",
                        sty.button2___8C1St
                      )}
                      color={"link"}
                      endIcon={
                        <Icon38Icon
                          className={classNames(projectcss.all, sty.svg__ql9ZQ)}
                          role={"img"}
                        />
                      }
                      link={`/contact`}
                      size={"minimal"}
                      startIcon={
                        <CheckSvgIcon
                          className={classNames(projectcss.all, sty.svg___3DwQ)}
                          role={"img"}
                        />
                      }
                      submitsForm={true}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__epFkH
                        )}
                      >
                        {"CONTACT"}
                      </div>
                    </Button2>
                  ) : null}
                </React.Fragment>
              }
              openButton={
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__s34Yn)}
                  displayHeight={"auto"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  src={"https://static1.plasmic.app/menu.svg"}
                />
              }
              responsiveBreakpoint={768}
            />
          ) : null}
          <section className={classNames(projectcss.all, sty.section__wnN91)} />

          <div className={classNames(projectcss.all, sty.freeBox___8U18)}>
            <div className={classNames(projectcss.all, sty.freeBox__tRdZ)}>
              <h1
                data-plasmic-name={"h1"}
                data-plasmic-override={overrides.h1}
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1
                )}
              >
                <React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ fontWeight: 500 }}
                  >
                    {
                      "\u00catre pr\u00e9venue des prochaines disponibilit\u00e9s"
                    }
                  </span>
                </React.Fragment>
              </h1>
            </div>
          </div>
          <section className={classNames(projectcss.all, sty.section__tw0Oy)}>
            <Embed
              data-plasmic-name={"embedHtml"}
              data-plasmic-override={overrides.embedHtml}
              className={classNames("__wab_instance", sty.embedHtml)}
              code={
                '<iframe src="https://app.weavely.ai/forms/1b9250d4-6bbf-4482-9b56-832974cf7e98" style="border: none; width: 100%; height: 100%;"></iframe>'
              }
            />
          </section>
          {(
            hasVariant(globalVariants, "screen", "tablet")
              ? true
              : hasVariant(globalVariants, "screen", "desktop")
              ? true
              : false
          ) ? (
            <section className={classNames(projectcss.all, sty.section__bThS9)}>
              <div className={classNames(projectcss.all, sty.freeBox__uShlZ)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__jgiUk)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__f3984)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__bhn97)}
                      displayHeight={"100px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/cloven/images/livraisonGratuiteOfferteExpeditionRapideFranceSvg.svg",
                        fullWidth: 1252,
                        fullHeight: 1199,
                        aspectRatio: 1.044204
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__fklda
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 500 }}
                        >
                          {"LIVRAISON OFFERTE"}
                        </span>
                      </React.Fragment>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__arAaM
                      )}
                    >
                      {
                        "D\u00e8s 50EUR d'achat\nExp\u00e9di\u00e9 en 24h \u00e0 48h\ndepuis la France m\u00e9trop."
                      }
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__ccyPz)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___87D3J)}
                      displayHeight={"100px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/cloven/images/serviceClientContactSvg.svg",
                        fullWidth: 1252,
                        fullHeight: 1199,
                        aspectRatio: 1.044204
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__a26Z7
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 500 }}
                        >
                          {"SERVICE CLIENT"}
                        </span>
                      </React.Fragment>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__x8CI
                      )}
                    >
                      {
                        "contact@cloven.fr\n01.85.09.27.19\nPrix d'un appel local"
                      }
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__xb6Ep)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___2Aaev)}
                      displayHeight={"100px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/cloven/images/paiementSecuriseEnPlusieursFoisPaypalCbVisaKlarnaMastercardSvg.svg",
                        fullWidth: 1252,
                        fullHeight: 1199,
                        aspectRatio: 1.044204
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__mo8EQ
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 500 }}
                        >
                          {"PAIEMENT S\u00c9CURIS\u00c9"}
                        </span>
                      </React.Fragment>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__pMkls
                      )}
                    >
                      {
                        "Facilit\u00e9 de paiement\n3x sans frais avec Alma\nCB/Visa/MasterCard/Paypal"
                      }
                    </div>
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__lfJef)}
                >
                  <Button2
                    className={classNames("__wab_instance", sty.button2__bv12)}
                    color={"link"}
                    endIcon={
                      <Icon38Icon
                        className={classNames(projectcss.all, sty.svg__mXuaa)}
                        role={"img"}
                      />
                    }
                    link={`/`}
                    size={"minimal"}
                    startIcon={
                      <CheckSvgIcon
                        className={classNames(projectcss.all, sty.svg__wp2Qa)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___6CG4D
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 600 }}
                        >
                          {"Cloven"}
                        </span>
                      </React.Fragment>
                    </div>
                  </Button2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ycaz1
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 400 }}
                      >
                        {"\uff5c"}
                      </span>
                      <React.Fragment>
                        {" La chance sourit aux audacieuses."}
                      </React.Fragment>
                    </React.Fragment>
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns___2Fotb)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__lQHo5)}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__xIlh)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___1ZLGu
                        )}
                      >
                        {"\u00c0 pROPOS"}
                      </div>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__miFwG
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__w0VHa
                            )}
                            role={"img"}
                          />
                        }
                        link={`/a-propos`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__cYc22
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__bYOf
                          )}
                        >
                          {"Une Marque Engag\u00e9e"}
                        </div>
                      </Button2>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__n7NR3
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__u5TH3
                            )}
                            role={"img"}
                          />
                        }
                        link={`/catalogue`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg___4RauP
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__hf2E
                          )}
                        >
                          {"Catalogue"}
                        </div>
                      </Button2>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2___20Lhs
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__fFnxG
                            )}
                            role={"img"}
                          />
                        }
                        link={`/faq`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__fup7Z
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__hzF56
                          )}
                        >
                          {"FAQ"}
                        </div>
                      </Button2>
                    </Stack__>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__kq7XV)}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__lZEaf)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___0K686
                        )}
                      >
                        {"MENTIONS G\u00c9N\u00c9RALES"}
                      </div>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__jP1X
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__pX0Tb
                            )}
                            role={"img"}
                          />
                        }
                        link={`/moyens-de-paiement`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__rMeYb
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__zKwHk
                          )}
                        >
                          {"Moyens de Paiement"}
                        </div>
                      </Button2>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2___3O5Uu
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__hTwHn
                            )}
                            role={"img"}
                          />
                        }
                        link={`/livraisons-et-retours`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__dXQfE
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__s0ONm
                          )}
                        >
                          {"Livraisons & Retours"}
                        </div>
                      </Button2>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__ySrrl
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__sFpvv
                            )}
                            role={"img"}
                          />
                        }
                        link={`/contact`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__ruxyb
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___52Dv9
                          )}
                        >
                          {"Contact"}
                        </div>
                      </Button2>
                    </Stack__>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__km0Ll)}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__ukPBm)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__eOFu
                        )}
                      >
                        {"INFORMATIONS L\u00c9GALES"}
                      </div>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__dyjib
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__opqHs
                            )}
                            role={"img"}
                          />
                        }
                        link={`/conditions-generales-de-vente`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg___5NiY9
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__oFk0H
                          )}
                        >
                          {"Conditions G\u00e9n\u00e9rales de Vente"}
                        </div>
                      </Button2>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__dpJwv
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__kBn1X
                            )}
                            role={"img"}
                          />
                        }
                        link={`/politique-de-confidentialite`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__jj9Yq
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__c73AL
                          )}
                        >
                          {"Politique de Confidentialit\u00e9"}
                        </div>
                      </Button2>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2___0XDlh
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__mtWju
                            )}
                            role={"img"}
                          />
                        }
                        link={`/mentions-legales`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__wRAwO
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__p1Dp4
                          )}
                        >
                          {"Mentions L\u00e9gales"}
                        </div>
                      </Button2>
                    </Stack__>
                  </div>
                </Stack__>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__apBcW
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 400 }}
                    >
                      {"\u00a9 2025 Cloven, Tous droits r\u00e9serv\u00e9s."}
                    </span>
                  </React.Fragment>
                </div>
              </div>
            </section>
          ) : null}
          {(hasVariant(globalVariants, "screen", "tablet") ? true : false) ? (
            <section
              className={classNames(projectcss.all, sty.section___2RUFo)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__nntCi)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__uV)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox___7JKgC)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__niQqr)}
                      displayHeight={"80px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"80px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/cloven/images/livraisonGratuiteOfferteExpeditionRapideFranceSvg.svg",
                        fullWidth: 1252,
                        fullHeight: 1199,
                        aspectRatio: 1.044204
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__q3TU9
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 500 }}
                        >
                          {"LIVRAISON OFFERTE"}
                        </span>
                      </React.Fragment>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___0Mr2O
                      )}
                    >
                      {
                        "D\u00e8s 50EUR d'achat\nExp\u00e9di\u00e9 en 24h \u00e0 48h\ndepuis la France m\u00e9trop."
                      }
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__o5OTz)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__xmRfs)}
                      displayHeight={"80px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"80px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/cloven/images/serviceClientContactSvg.svg",
                        fullWidth: 1252,
                        fullHeight: 1199,
                        aspectRatio: 1.044204
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__twoD
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 500 }}
                        >
                          {"SERVICE CLIENT"}
                        </span>
                      </React.Fragment>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__idaUe
                      )}
                    >
                      {
                        "contact@cloven.fr\n01.85.09.27.19\nPrix d'un appel local"
                      }
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__gcTc)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__nt8Ok)}
                      displayHeight={"80px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"80px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/cloven/images/paiementSecuriseEnPlusieursFoisPaypalCbVisaKlarnaMastercardSvg.svg",
                        fullWidth: 1252,
                        fullHeight: 1199,
                        aspectRatio: 1.044204
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__gOtGz
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 500 }}
                        >
                          {"PAIEMENT S\u00c9CURIS\u00c9"}
                        </span>
                      </React.Fragment>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__bw4CE
                      )}
                    >
                      {
                        "Facilit\u00e9 de paiement\n3x sans frais avec Alma\nCB/Visa/MasterCard/Paypal"
                      }
                    </div>
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__x3Sze)}
                >
                  <Button2
                    className={classNames("__wab_instance", sty.button2__yRLv4)}
                    color={"link"}
                    endIcon={
                      <Icon38Icon
                        className={classNames(projectcss.all, sty.svg__nFmLx)}
                        role={"img"}
                      />
                    }
                    link={`/`}
                    size={"minimal"}
                    startIcon={
                      <CheckSvgIcon
                        className={classNames(projectcss.all, sty.svg__dPs42)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__bMwTo
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 600 }}
                        >
                          {"Cloven"}
                        </span>
                      </React.Fragment>
                    </div>
                  </Button2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gGUya
                    )}
                  >
                    {"La chance sourit aux audacieuses."}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qbtqS
                    )}
                  >
                    {"https://www.youtube.com/watch?v=dev6XJpwmbU"}
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns__rlyQu)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__kzqRd)}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__jN88)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ge7U8
                        )}
                      >
                        {"\u00c0 pROPOS"}
                      </div>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2___5HmzU
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__nXTa
                            )}
                            role={"img"}
                          />
                        }
                        link={`/a-propos`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__atSvl
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__t07BK
                          )}
                        >
                          {"Une Marque Engag\u00e9e"}
                        </div>
                      </Button2>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__nmAi7
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg___9PUg0
                            )}
                            role={"img"}
                          />
                        }
                        link={`/catalogue`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__vccA3
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__wRlKn
                          )}
                        >
                          {"Catalogue"}
                        </div>
                      </Button2>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__dklLu
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg___5XbC
                            )}
                            role={"img"}
                          />
                        }
                        link={`/faq`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__wxU5E
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__sEbzX
                          )}
                        >
                          {"FAQ"}
                        </div>
                      </Button2>
                    </Stack__>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__kG9Mc)}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__lgKfk)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___3WvY7
                        )}
                      >
                        {"MENTIONS G\u00c9N\u00c9RALES"}
                      </div>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__uvSyj
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__mPkwT
                            )}
                            role={"img"}
                          />
                        }
                        link={`/moyens-de-paiement`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__kwYv4
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__skASp
                          )}
                        >
                          {"Moyens de Paiement"}
                        </div>
                      </Button2>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__zzIbD
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg___1SjB
                            )}
                            role={"img"}
                          />
                        }
                        link={`/livraisons-et-retours`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__naQMf
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__uWb8A
                          )}
                        >
                          {"Livraisons & Retours"}
                        </div>
                      </Button2>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__qgXto
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__vIxK
                            )}
                            role={"img"}
                          />
                        }
                        link={`/contact`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__psmLz
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__r022
                          )}
                        >
                          {"Contact"}
                        </div>
                      </Button2>
                    </Stack__>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__uKPgx)}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__na7Hd)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__ugW7X
                        )}
                      >
                        {"INFORMATIONS L\u00c9GALES"}
                      </div>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2___1YQ0Q
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__r5Bu
                            )}
                            role={"img"}
                          />
                        }
                        link={`/conditions-generales-de-vente`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__eg4Mk
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__vkmvy
                          )}
                        >
                          {"Conditions G\u00e9n\u00e9rales de Vente"}
                        </div>
                      </Button2>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2___2YrMm
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__zSrRb
                            )}
                            role={"img"}
                          />
                        }
                        link={`/politique-de-confidentialite`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg___8KVwi
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__k1LxX
                          )}
                        >
                          {"Politique de Confidentialit\u00e9"}
                        </div>
                      </Button2>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__fpRmN
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg___6KlL
                            )}
                            role={"img"}
                          />
                        }
                        link={`/mentions-legales`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__ji2Ys
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__szGi
                          )}
                        >
                          {"Mentions L\u00e9gales"}
                        </div>
                      </Button2>
                    </Stack__>
                  </div>
                </Stack__>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__d31QB
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 400 }}
                    >
                      {"\u00a9 2025 Cloven, Tous droits r\u00e9serv\u00e9s."}
                    </span>
                  </React.Fragment>
                </div>
              </div>
            </section>
          ) : null}
          {(
            hasVariant(globalVariants, "screen", "tablet")
              ? true
              : hasVariant(globalVariants, "screen", "desktop")
              ? true
              : hasVariant(globalVariants, "screen", "bigScreen")
              ? true
              : false
          ) ? (
            <section className={classNames(projectcss.all, sty.section___4TJz)}>
              <div className={classNames(projectcss.all, sty.freeBox__vFvCn)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__gs2K)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__vYYlw)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__djEV)}
                      displayHeight={"130px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"130px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/cloven/images/livraisonGratuiteOfferteExpeditionRapideFranceSvg.svg",
                        fullWidth: 1252,
                        fullHeight: 1199,
                        aspectRatio: 1.044204
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__gojW7
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 500 }}
                        >
                          {"LIVRAISON OFFERTE"}
                        </span>
                      </React.Fragment>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__uW7Fz
                      )}
                    >
                      {
                        "D\u00e8s 50EUR d'achat\nExp\u00e9di\u00e9 en 24h \u00e0 48h\ndepuis la France m\u00e9trop."
                      }
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__lYz8U)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__dAr97)}
                      displayHeight={"130px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"130px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/cloven/images/serviceClientContactSvg.svg",
                        fullWidth: 1252,
                        fullHeight: 1199,
                        aspectRatio: 1.044204
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xBm4N
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 500 }}
                        >
                          {"SERVICE CLIENT"}
                        </span>
                      </React.Fragment>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__gxW
                      )}
                    >
                      {
                        "contact@cloven.fr\n01.85.09.27.19\nPrix d'un appel local"
                      }
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__xhsnl)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__qZsSh)}
                      displayHeight={"130px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"130px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/cloven/images/paiementSecuriseEnPlusieursFoisPaypalCbVisaKlarnaMastercardSvg.svg",
                        fullWidth: 1252,
                        fullHeight: 1199,
                        aspectRatio: 1.044204
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__wSyKp
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 500 }}
                        >
                          {"PAIEMENT S\u00c9CURIS\u00c9"}
                        </span>
                      </React.Fragment>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___5Uh3A
                      )}
                    >
                      {
                        "Facilit\u00e9 de paiement\n3x sans frais avec Alma\nCB/Visa/MasterCard/Paypal"
                      }
                    </div>
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__e2J0)}
                >
                  <Button2
                    className={classNames("__wab_instance", sty.button2__f7Qdd)}
                    color={"link"}
                    endIcon={
                      <Icon38Icon
                        className={classNames(projectcss.all, sty.svg__iuKnb)}
                        role={"img"}
                      />
                    }
                    link={`/`}
                    size={"minimal"}
                    startIcon={
                      <CheckSvgIcon
                        className={classNames(projectcss.all, sty.svg__tkY0P)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ik83A
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 600 }}
                        >
                          {"Cloven"}
                        </span>
                      </React.Fragment>
                    </div>
                  </Button2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__wmMuf
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 400 }}
                      >
                        {"\uff5c"}
                      </span>
                      <React.Fragment>
                        {" La chance sourit aux audacieuses."}
                      </React.Fragment>
                    </React.Fragment>
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns__flcCk)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__bLUpe)}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__mW40)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__uKebv
                        )}
                      >
                        {"\u00c0 pROPOS"}
                      </div>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__zaCbj
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg___33F3E
                            )}
                            role={"img"}
                          />
                        }
                        link={`/a-propos`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__h9Yz
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___3X0Ex
                          )}
                        >
                          {"Une Marque Engag\u00e9e"}
                        </div>
                      </Button2>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2___1ZTn9
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__dGHuq
                            )}
                            role={"img"}
                          />
                        }
                        link={`/catalogue`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__gntuI
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__nE6Lc
                          )}
                        >
                          {"Catalogue"}
                        </div>
                      </Button2>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__lzBpE
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg___2LZnw
                            )}
                            role={"img"}
                          />
                        }
                        link={`/faq`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__jlUtv
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__pqOpn
                          )}
                        >
                          {"FAQ"}
                        </div>
                      </Button2>
                    </Stack__>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__fpZ7C)}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__xFaoo)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__aJns
                        )}
                      >
                        {"MENTIONS G\u00c9N\u00c9RALES"}
                      </div>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__wsIQq
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__hDFeT
                            )}
                            role={"img"}
                          />
                        }
                        link={`/moyens-de-paiement`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg___9RIZx
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__eRryc
                          )}
                        >
                          {"Moyens de Paiement"}
                        </div>
                      </Button2>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__mwAfg
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__mMfqc
                            )}
                            role={"img"}
                          />
                        }
                        link={`/livraisons-et-retours`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__xAq0G
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__mxSHy
                          )}
                        >
                          {"Livraisons & Retours"}
                        </div>
                      </Button2>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__t5Kmq
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__kq53W
                            )}
                            role={"img"}
                          />
                        }
                        link={`/contact`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__ymEr3
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__lAyW
                          )}
                        >
                          {"Contact"}
                        </div>
                      </Button2>
                    </Stack__>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__ckHiy)}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__zoI9W)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__llWkB
                        )}
                      >
                        {"INFORMATIONS L\u00c9GALES"}
                      </div>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__eo07F
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__azEvc
                            )}
                            role={"img"}
                          />
                        }
                        link={`/conditions-generales-de-vente`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__vlVkl
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__pyutV
                          )}
                        >
                          {"Conditions G\u00e9n\u00e9rales de Vente"}
                        </div>
                      </Button2>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__jtdN
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__d1WsR
                            )}
                            role={"img"}
                          />
                        }
                        link={`/politique-de-confidentialite`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__xGzqc
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__vv6Ft
                          )}
                        >
                          {"Politique de Confidentialit\u00e9"}
                        </div>
                      </Button2>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__waZwD
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__wpFkx
                            )}
                            role={"img"}
                          />
                        }
                        link={`/mentions-legales`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__aC9Pl
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__g66I
                          )}
                        >
                          {"Mentions L\u00e9gales"}
                        </div>
                      </Button2>
                    </Stack__>
                  </div>
                </Stack__>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__g1A1
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 400 }}
                    >
                      {"\u00a9 2025 Cloven, Tous droits r\u00e9serv\u00e9s."}
                    </span>
                  </React.Fragment>
                </div>
              </div>
            </section>
          ) : null}
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  formulaireDeCommande: [
    "formulaireDeCommande",
    "navigationBar",
    "h1",
    "embedHtml"
  ],
  navigationBar: ["navigationBar"],
  h1: ["h1"],
  embedHtml: ["embedHtml"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  formulaireDeCommande: "div";
  navigationBar: typeof NavigationBar;
  h1: "h1";
  embedHtml: typeof Embed;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicFormulaireDeCommande__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicFormulaireDeCommande__VariantsArgs;
    args?: PlasmicFormulaireDeCommande__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicFormulaireDeCommande__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicFormulaireDeCommande__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicFormulaireDeCommande__ArgProps,
          internalVariantPropNames: PlasmicFormulaireDeCommande__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicFormulaireDeCommande__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "formulaireDeCommande") {
    func.displayName = "PlasmicFormulaireDeCommande";
  } else {
    func.displayName = `PlasmicFormulaireDeCommande.${nodeName}`;
  }
  return func;
}

export const PlasmicFormulaireDeCommande = Object.assign(
  // Top-level PlasmicFormulaireDeCommande renders the root element
  makeNodeComponent("formulaireDeCommande"),
  {
    // Helper components rendering sub-elements
    navigationBar: makeNodeComponent("navigationBar"),
    h1: makeNodeComponent("h1"),
    embedHtml: makeNodeComponent("embedHtml"),

    // Metadata about props expected for PlasmicFormulaireDeCommande
    internalVariantProps: PlasmicFormulaireDeCommande__VariantProps,
    internalArgProps: PlasmicFormulaireDeCommande__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Formulaire de Commande",
      description:
        "Soyez prévenue des prochaines disponibilités en remplissant le formulaire de commande. Sélectionnez votre taille et articles de votre choix pour être notifiée.",
      ogImageSrc:
        "https://site-assets.plasmic.app/9c84777ee8b0e9a31b311fd8d91ccf0a.jpg",
      canonical: ""
    }
  }
);

export default PlasmicFormulaireDeCommande;
/* prettier-ignore-end */
