// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 8PwgGRpqC1sfX2e6Md5Z7h
// Component: f-dSdA_Pnv6-

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { NavigationBar } from "@plasmicpkgs/plasmic-nav";
import Button2 from "../../Button2"; // plasmic-import: UFQeZdp76e18/component
import { Embed } from "@plasmicpkgs/plasmic-basic-components";
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";

import { useScreenVariants as useScreenVariantsikbnv5YY9ZVd } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: ikbnv5yY9zVD/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 8PwgGRpqC1sfX2e6Md5Z7h/projectcss
import sty from "./PlasmicContact.module.css"; // plasmic-import: f-dSdA_Pnv6-/css

import CheckSvgIcon from "./icons/PlasmicIcon__CheckSvg"; // plasmic-import: ftHUtpQxxIrf/icon
import Icon38Icon from "./icons/PlasmicIcon__Icon38"; // plasmic-import: sl6S8_6N7zOW/icon

createPlasmicElementProxy;

export type PlasmicContact__VariantMembers = {};
export type PlasmicContact__VariantsArgs = {};
type VariantPropType = keyof PlasmicContact__VariantsArgs;
export const PlasmicContact__VariantProps = new Array<VariantPropType>();

export type PlasmicContact__ArgsType = {};
type ArgPropType = keyof PlasmicContact__ArgsType;
export const PlasmicContact__ArgProps = new Array<ArgPropType>();

export type PlasmicContact__OverridesType = {
  contact?: Flex__<"div">;
  navigationBar?: Flex__<typeof NavigationBar>;
  h1?: Flex__<"h1">;
  embedHtml?: Flex__<typeof Embed>;
};

export interface DefaultContactProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicContact__RenderFunc(props: {
  variants: PlasmicContact__VariantsArgs;
  args: PlasmicContact__ArgsType;
  overrides: PlasmicContact__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsikbnv5YY9ZVd()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary_large_image" />
        <title key="title">{PlasmicContact.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicContact.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicContact.pageMetadata.title}
        />
        <meta
          key="description"
          name="description"
          content={PlasmicContact.pageMetadata.description}
        />
        <meta
          key="og:description"
          property="og:description"
          content={PlasmicContact.pageMetadata.description}
        />
        <meta
          key="twitter:description"
          name="twitter:description"
          content={PlasmicContact.pageMetadata.description}
        />
        <meta
          key="og:image"
          property="og:image"
          content={PlasmicContact.pageMetadata.ogImageSrc}
        />
        <meta
          key="twitter:image"
          name="twitter:image"
          content={PlasmicContact.pageMetadata.ogImageSrc}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"contact"}
          data-plasmic-override={overrides.contact}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.contact
          )}
        >
          <NavigationBar
            data-plasmic-name={"navigationBar"}
            data-plasmic-override={overrides.navigationBar}
            brand={
              (
                hasVariant(globalVariants, "screen", "desktop")
                  ? true
                  : hasVariant(globalVariants, "screen", "bigScreen")
                  ? true
                  : false
              ) ? (
                <Button2
                  className={classNames("__wab_instance", sty.button2__rUein)}
                  color={"link"}
                  endIcon={
                    <Icon38Icon
                      className={classNames(projectcss.all, sty.svg__co3YK)}
                      role={"img"}
                    />
                  }
                  link={`/`}
                  size={"minimal"}
                  startIcon={
                    <CheckSvgIcon
                      className={classNames(projectcss.all, sty.svg__bhEb2)}
                      role={"img"}
                    />
                  }
                  submitsForm={true}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__oxTfJ
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 600 }}
                      >
                        {"Cloven"}
                      </span>
                    </React.Fragment>
                  </div>
                </Button2>
              ) : null
            }
            className={classNames("__wab_instance", sty.navigationBar)}
            closeButton={
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__nlLJk)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                src={"https://static1.plasmic.app/close.svg"}
              />
            }
            itemsGap={8}
            menuItems={
              <React.Fragment>
                {(
                  hasVariant(globalVariants, "screen", "desktop")
                    ? true
                    : hasVariant(globalVariants, "screen", "bigScreen")
                    ? true
                    : false
                ) ? (
                  <Button2
                    className={classNames("__wab_instance", sty.button2__tzjCj)}
                    color={"link"}
                    endIcon={
                      <Icon38Icon
                        className={classNames(projectcss.all, sty.svg__qcXse)}
                        role={"img"}
                      />
                    }
                    link={`/catalogue`}
                    size={"minimal"}
                    startIcon={
                      <CheckSvgIcon
                        className={classNames(projectcss.all, sty.svg___0WbK3)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__bXrYf
                      )}
                    >
                      {"COLLECTION"}
                    </div>
                  </Button2>
                ) : null}
                {(
                  hasVariant(globalVariants, "screen", "desktop")
                    ? true
                    : hasVariant(globalVariants, "screen", "bigScreen")
                    ? true
                    : false
                ) ? (
                  <Button2
                    className={classNames("__wab_instance", sty.button2___7KBQ)}
                    color={"link"}
                    endIcon={
                      <Icon38Icon
                        className={classNames(projectcss.all, sty.svg__yegtq)}
                        role={"img"}
                      />
                    }
                    link={`/a-propos`}
                    size={"minimal"}
                    startIcon={
                      <CheckSvgIcon
                        className={classNames(projectcss.all, sty.svg__yN19H)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__g5C3I
                      )}
                    >
                      {"\u00c0 PROPOS"}
                    </div>
                  </Button2>
                ) : null}
                {(
                  hasVariant(globalVariants, "screen", "desktop")
                    ? true
                    : hasVariant(globalVariants, "screen", "bigScreen")
                    ? true
                    : false
                ) ? (
                  <Button2
                    className={classNames("__wab_instance", sty.button2__bbylH)}
                    color={"link"}
                    endIcon={
                      <Icon38Icon
                        className={classNames(projectcss.all, sty.svg__fZi4R)}
                        role={"img"}
                      />
                    }
                    link={`/contact`}
                    size={"minimal"}
                    startIcon={
                      <CheckSvgIcon
                        className={classNames(projectcss.all, sty.svg__gsr6Q)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__faweK
                      )}
                    >
                      {"CONTACT"}
                    </div>
                  </Button2>
                ) : null}
              </React.Fragment>
            }
            openButton={
              <PlasmicImg__
                alt={""}
                className={classNames(sty.img__hhYGk)}
                displayHeight={"auto"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                src={"https://static1.plasmic.app/menu.svg"}
              />
            }
            responsiveBreakpoint={768}
          />

          <section className={classNames(projectcss.all, sty.section__xQkL9)} />

          <div className={classNames(projectcss.all, sty.freeBox__bih3)}>
            <div className={classNames(projectcss.all, sty.freeBox__hs8KR)}>
              <h1
                data-plasmic-name={"h1"}
                data-plasmic-override={overrides.h1}
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1
                )}
              >
                <React.Fragment>
                  <span
                    className={"plasmic_default__all plasmic_default__span"}
                    style={{ fontWeight: 500 }}
                  >
                    {"Contact"}
                  </span>
                </React.Fragment>
              </h1>
            </div>
          </div>
          <section className={classNames(projectcss.all, sty.section__ymICf)}>
            <div className={classNames(projectcss.all, sty.freeBox__oxurV)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__cHrH
                )}
              >
                {
                  "Une question ? Consultez notre section FAQ, sinon, contactez-nous directement."
                }
              </div>
              <div className={classNames(projectcss.all, sty.columns__yTob5)}>
                <div className={classNames(projectcss.all, sty.column__yr1Kx)}>
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__qrYyI)}
                    displayHeight={"100%"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: "/plasmic/cloven/images/traceSvg.svg",
                      fullWidth: 500,
                      fullHeight: 500,
                      aspectRatio: 1
                    }}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__ohbUj)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__dRb6
                    )}
                  >
                    {
                      "contact@cloven.fr\n01.85.09.27.19 du lundi au vendredi de 9h \u00e0 18h."
                    }
                  </div>
                  <Embed
                    data-plasmic-name={"embedHtml"}
                    data-plasmic-override={overrides.embedHtml}
                    className={classNames("__wab_instance", sty.embedHtml)}
                    code={
                      '<iframe data-tally-src="https://tally.so/embed/n91pQK?alignLeft=1&hideTitle=1&transparentBackground=1&dynamicHeight=1" loading="lazy" width="100%" height="30" frameborder="0" marginheight="0" marginwidth="0" title="Formulaire de contact"></iframe><script>var d=document,w="https://tally.so/widgets/embed.js",v=function(){"undefined"!=typeof Tally?Tally.loadEmbeds():d.querySelectorAll("iframe[data-tally-src]:not([src])").forEach((function(e){e.src=e.dataset.tallySrc}))};if("undefined"!=typeof Tally)v();else if(d.querySelector(\'script[src="\'+w+\'"]\')==null){var s=d.createElement("script");s.src=w,s.onload=v,s.onerror=v,d.body.appendChild(s);}</script>\r\n'
                    }
                  />
                </div>
              </div>
            </div>
          </section>
          {(hasVariant(globalVariants, "screen", "tablet") ? true : false) ? (
            <section
              className={classNames(projectcss.all, sty.section___0HHjP)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__cdYw)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__knOew)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox___48B0)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__y7CDa)}
                      displayHeight={"80px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"80px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/cloven/images/livraisonGratuiteOfferteExpeditionRapideFranceSvg.svg",
                        fullWidth: 1252,
                        fullHeight: 1199,
                        aspectRatio: 1.044204
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___7Pv5X
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 500 }}
                        >
                          {"LIVRAISON OFFERTE"}
                        </span>
                      </React.Fragment>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xCkI
                      )}
                    >
                      {
                        "D\u00e8s 50EUR d'achat\nExp\u00e9di\u00e9 en 24h \u00e0 48h\ndepuis la France m\u00e9trop."
                      }
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___7VG5F)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___21LO1)}
                      displayHeight={"80px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"80px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/cloven/images/serviceClientContactSvg.svg",
                        fullWidth: 1252,
                        fullHeight: 1199,
                        aspectRatio: 1.044204
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___3QF4S
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 500 }}
                        >
                          {"SERVICE CLIENT"}
                        </span>
                      </React.Fragment>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__fo2X
                      )}
                    >
                      {
                        "contact@cloven.fr\n01.85.09.27.19\nPrix d'un appel local"
                      }
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__bOsYc)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__gv4YZ)}
                      displayHeight={"80px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"80px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/cloven/images/paiementSecuriseEnPlusieursFoisPaypalCbVisaKlarnaMastercardSvg.svg",
                        fullWidth: 1252,
                        fullHeight: 1199,
                        aspectRatio: 1.044204
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__uiNn5
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 500 }}
                        >
                          {"PAIEMENT S\u00c9CURIS\u00c9"}
                        </span>
                      </React.Fragment>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__stfpG
                      )}
                    >
                      {
                        "Facilit\u00e9 de paiement\n3x sans frais avec Alma\nCB/Visa/MasterCard/Paypal"
                      }
                    </div>
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__jFoHc)}
                >
                  <Button2
                    className={classNames("__wab_instance", sty.button2__snHe)}
                    color={"link"}
                    endIcon={
                      <Icon38Icon
                        className={classNames(projectcss.all, sty.svg__zfHfO)}
                        role={"img"}
                      />
                    }
                    link={`/`}
                    size={"minimal"}
                    startIcon={
                      <CheckSvgIcon
                        className={classNames(projectcss.all, sty.svg__fEmx7)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__bxmT
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 600 }}
                        >
                          {"Cloven"}
                        </span>
                      </React.Fragment>
                    </div>
                  </Button2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__gVs0
                    )}
                  >
                    {"La chance sourit aux audacieuses."}
                  </div>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__oELkB
                    )}
                  >
                    {"https://www.youtube.com/watch?v=dev6XJpwmbU"}
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns__pkjqh)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__w6F4D)}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__xudod)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__rogQ
                        )}
                      >
                        {"\u00c0 pROPOS"}
                      </div>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__zuP7W
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__y7RYz
                            )}
                            role={"img"}
                          />
                        }
                        link={`/a-propos`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__ni2Vx
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__xqp93
                          )}
                        >
                          {"Une Marque Engag\u00e9e"}
                        </div>
                      </Button2>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2___3DkIz
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__xArcp
                            )}
                            role={"img"}
                          />
                        }
                        link={`/catalogue`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__xJTjk
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__h5Hy
                          )}
                        >
                          {"Catalogue"}
                        </div>
                      </Button2>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__tqVzw
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg___6MBmi
                            )}
                            role={"img"}
                          />
                        }
                        link={`/faq`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__lq4MC
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__qy2B
                          )}
                        >
                          {"FAQ"}
                        </div>
                      </Button2>
                    </Stack__>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__kBa1L)}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___46XnV
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__bHVyX
                        )}
                      >
                        {"MENTIONS G\u00c9N\u00c9RALES"}
                      </div>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__w8P4K
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__vOcIu
                            )}
                            role={"img"}
                          />
                        }
                        link={`/moyens-de-paiement`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__d1Rwt
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__tiGlo
                          )}
                        >
                          {"Moyens de Paiement"}
                        </div>
                      </Button2>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__mG3Wb
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__v8LFw
                            )}
                            role={"img"}
                          />
                        }
                        link={`/livraisons-et-retours`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__hezpF
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___5ZmX
                          )}
                        >
                          {"Livraisons & Retours"}
                        </div>
                      </Button2>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__cQ9Sy
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__zUm1H
                            )}
                            role={"img"}
                          />
                        }
                        link={`/contact`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__lq1GB
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__wctew
                          )}
                        >
                          {"Contact"}
                        </div>
                      </Button2>
                    </Stack__>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__jtTqi)}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__hk3Zm)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__jUhT
                        )}
                      >
                        {"INFORMATIONS L\u00c9GALES"}
                      </div>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__ysifP
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__q8LHy
                            )}
                            role={"img"}
                          />
                        }
                        link={`/conditions-generales-de-vente`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg___8LxC
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__pWi1J
                          )}
                        >
                          {"Conditions G\u00e9n\u00e9rales de Vente"}
                        </div>
                      </Button2>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__hmjhS
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__tcWc8
                            )}
                            role={"img"}
                          />
                        }
                        link={`/politique-de-confidentialite`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__l6ES
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__i2DK2
                          )}
                        >
                          {"Politique de Confidentialit\u00e9"}
                        </div>
                      </Button2>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2___4Vw7G
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__wB6N
                            )}
                            role={"img"}
                          />
                        }
                        link={`/mentions-legales`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__yZwcj
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__soMCg
                          )}
                        >
                          {"Mentions L\u00e9gales"}
                        </div>
                      </Button2>
                    </Stack__>
                  </div>
                </Stack__>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___4ZfRg
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 400 }}
                    >
                      {"\u00a9 2025 Cloven, Tous droits r\u00e9serv\u00e9s."}
                    </span>
                  </React.Fragment>
                </div>
              </div>
            </section>
          ) : null}
          {(
            hasVariant(globalVariants, "screen", "tablet")
              ? true
              : hasVariant(globalVariants, "screen", "desktop")
              ? true
              : false
          ) ? (
            <section className={classNames(projectcss.all, sty.section__jlns)}>
              <div className={classNames(projectcss.all, sty.freeBox__ooS2S)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__h9E2H)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__gDUbe)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__mdFv3)}
                      displayHeight={"100px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/cloven/images/livraisonGratuiteOfferteExpeditionRapideFranceSvg.svg",
                        fullWidth: 1252,
                        fullHeight: 1199,
                        aspectRatio: 1.044204
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___9TDbG
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 500 }}
                        >
                          {"LIVRAISON OFFERTE"}
                        </span>
                      </React.Fragment>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__qYyUl
                      )}
                    >
                      {
                        "D\u00e8s 50EUR d'achat\nExp\u00e9di\u00e9 en 24h \u00e0 48h\ndepuis la France m\u00e9trop."
                      }
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__mfjW)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__bpqmh)}
                      displayHeight={"100px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/cloven/images/serviceClientContactSvg.svg",
                        fullWidth: 1252,
                        fullHeight: 1199,
                        aspectRatio: 1.044204
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__gq2Pj
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 500 }}
                        >
                          {"SERVICE CLIENT"}
                        </span>
                      </React.Fragment>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__nEcM2
                      )}
                    >
                      {
                        "contact@cloven.fr\n01.85.09.27.19\nPrix d'un appel local"
                      }
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__xhr5P)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__v7Ot7)}
                      displayHeight={"100px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/cloven/images/paiementSecuriseEnPlusieursFoisPaypalCbVisaKlarnaMastercardSvg.svg",
                        fullWidth: 1252,
                        fullHeight: 1199,
                        aspectRatio: 1.044204
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__wD4Om
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 500 }}
                        >
                          {"PAIEMENT S\u00c9CURIS\u00c9"}
                        </span>
                      </React.Fragment>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__dEeq2
                      )}
                    >
                      {
                        "Facilit\u00e9 de paiement\n3x sans frais avec Alma\nCB/Visa/MasterCard/Paypal"
                      }
                    </div>
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__t5H4T)}
                >
                  <Button2
                    className={classNames("__wab_instance", sty.button2__rgFsb)}
                    color={"link"}
                    endIcon={
                      <Icon38Icon
                        className={classNames(projectcss.all, sty.svg__sx00B)}
                        role={"img"}
                      />
                    }
                    link={`/`}
                    size={"minimal"}
                    startIcon={
                      <CheckSvgIcon
                        className={classNames(projectcss.all, sty.svg__uthLa)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__ioQt8
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 600 }}
                        >
                          {"Cloven"}
                        </span>
                      </React.Fragment>
                    </div>
                  </Button2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__muOxo
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 400 }}
                      >
                        {"\uff5c"}
                      </span>
                      <React.Fragment>
                        {" La chance sourit aux audacieuses."}
                      </React.Fragment>
                    </React.Fragment>
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns__jr1Hu)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__wwI1U)}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__lZyR)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___3ZHy2
                        )}
                      >
                        {"\u00c0 pROPOS"}
                      </div>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__juo9M
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__tnyN
                            )}
                            role={"img"}
                          />
                        }
                        link={`/a-propos`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__dfRkU
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__wIkEe
                          )}
                        >
                          {"Une Marque Engag\u00e9e"}
                        </div>
                      </Button2>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__cpxaq
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__cnvRu
                            )}
                            role={"img"}
                          />
                        }
                        link={`/catalogue`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__nf7L
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__gKje
                          )}
                        >
                          {"Catalogue"}
                        </div>
                      </Button2>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__vDinZ
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg___4PpGk
                            )}
                            role={"img"}
                          />
                        }
                        link={`/faq`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__lNqr7
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__lMsex
                          )}
                        >
                          {"FAQ"}
                        </div>
                      </Button2>
                    </Stack__>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column___8Eac)}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___9VfVd
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__e6D4I
                        )}
                      >
                        {"MENTIONS G\u00c9N\u00c9RALES"}
                      </div>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__hudX
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__h9PaW
                            )}
                            role={"img"}
                          />
                        }
                        link={`/moyens-de-paiement`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__vSisV
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__a0Z7R
                          )}
                        >
                          {"Moyens de Paiement"}
                        </div>
                      </Button2>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__iwxtM
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__ecVbk
                            )}
                            role={"img"}
                          />
                        }
                        link={`/livraisons-et-retours`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg___9J0
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__egYnt
                          )}
                        >
                          {"Livraisons & Retours"}
                        </div>
                      </Button2>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__sbuGi
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__f3JJc
                            )}
                            role={"img"}
                          />
                        }
                        link={`/contact`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__xad4
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__gaWbc
                          )}
                        >
                          {"Contact"}
                        </div>
                      </Button2>
                    </Stack__>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__yq1Gh)}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__faaAa)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__fm11V
                        )}
                      >
                        {"INFORMATIONS L\u00c9GALES"}
                      </div>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__hOc
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__axfxJ
                            )}
                            role={"img"}
                          />
                        }
                        link={`/conditions-generales-de-vente`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__yO05P
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__zMi
                          )}
                        >
                          {"Conditions G\u00e9n\u00e9rales de Vente"}
                        </div>
                      </Button2>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__duNMu
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__sow5X
                            )}
                            role={"img"}
                          />
                        }
                        link={`/politique-de-confidentialite`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__mq6T3
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__jKfdd
                          )}
                        >
                          {"Politique de Confidentialit\u00e9"}
                        </div>
                      </Button2>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__lQsEf
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__kdEn
                            )}
                            role={"img"}
                          />
                        }
                        link={`/mentions-legales`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg___4QgN9
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___0PoEm
                          )}
                        >
                          {"Mentions L\u00e9gales"}
                        </div>
                      </Button2>
                    </Stack__>
                  </div>
                </Stack__>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__cLwFs
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 400 }}
                    >
                      {"\u00a9 2025 Cloven, Tous droits r\u00e9serv\u00e9s."}
                    </span>
                  </React.Fragment>
                </div>
              </div>
            </section>
          ) : null}
          {(
            hasVariant(globalVariants, "screen", "tablet")
              ? true
              : hasVariant(globalVariants, "screen", "desktop")
              ? true
              : hasVariant(globalVariants, "screen", "bigScreen")
              ? true
              : false
          ) ? (
            <section
              className={classNames(projectcss.all, sty.section___8WhvY)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__sfqo)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__qw2F)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__ny9U6)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__jpSZb)}
                      displayHeight={"130px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"130px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/cloven/images/livraisonGratuiteOfferteExpeditionRapideFranceSvg.svg",
                        fullWidth: 1252,
                        fullHeight: 1199,
                        aspectRatio: 1.044204
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___6TC64
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 500 }}
                        >
                          {"LIVRAISON OFFERTE"}
                        </span>
                      </React.Fragment>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__w7Xym
                      )}
                    >
                      {
                        "D\u00e8s 50EUR d'achat\nExp\u00e9di\u00e9 en 24h \u00e0 48h\ndepuis la France m\u00e9trop."
                      }
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox___7FC7N)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img__p60GY)}
                      displayHeight={"130px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"130px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/cloven/images/serviceClientContactSvg.svg",
                        fullWidth: 1252,
                        fullHeight: 1199,
                        aspectRatio: 1.044204
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__jG8E7
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 500 }}
                        >
                          {"SERVICE CLIENT"}
                        </span>
                      </React.Fragment>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___1ANyS
                      )}
                    >
                      {
                        "contact@cloven.fr\n01.85.09.27.19\nPrix d'un appel local"
                      }
                    </div>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__n8DDk)}
                  >
                    <PlasmicImg__
                      alt={""}
                      className={classNames(sty.img___2GzHu)}
                      displayHeight={"130px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"100%"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"130px"}
                      loading={"lazy"}
                      src={{
                        src: "/plasmic/cloven/images/paiementSecuriseEnPlusieursFoisPaypalCbVisaKlarnaMastercardSvg.svg",
                        fullWidth: 1252,
                        fullHeight: 1199,
                        aspectRatio: 1.044204
                      }}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__qk0OC
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 500 }}
                        >
                          {"PAIEMENT S\u00c9CURIS\u00c9"}
                        </span>
                      </React.Fragment>
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__eGvNg
                      )}
                    >
                      {
                        "Facilit\u00e9 de paiement\n3x sans frais avec Alma\nCB/Visa/MasterCard/Paypal"
                      }
                    </div>
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___6IV2I)}
                >
                  <Button2
                    className={classNames("__wab_instance", sty.button2__tdntQ)}
                    color={"link"}
                    endIcon={
                      <Icon38Icon
                        className={classNames(projectcss.all, sty.svg__qdcrt)}
                        role={"img"}
                      />
                    }
                    link={`/`}
                    size={"minimal"}
                    startIcon={
                      <CheckSvgIcon
                        className={classNames(projectcss.all, sty.svg__kdYmN)}
                        role={"img"}
                      />
                    }
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__vPauW
                      )}
                    >
                      <React.Fragment>
                        <span
                          className={
                            "plasmic_default__all plasmic_default__span"
                          }
                          style={{ fontWeight: 600 }}
                        >
                          {"Cloven"}
                        </span>
                      </React.Fragment>
                    </div>
                  </Button2>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__nef0A
                    )}
                  >
                    <React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontWeight: 400 }}
                      >
                        {"\uff5c"}
                      </span>
                      <React.Fragment>
                        {" La chance sourit aux audacieuses."}
                      </React.Fragment>
                    </React.Fragment>
                  </div>
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.columns__bdlk6)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column__qnFy2)}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__lXgsI)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__tMvrX
                        )}
                      >
                        {"\u00c0 pROPOS"}
                      </div>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__cuwp
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__hmNfp
                            )}
                            role={"img"}
                          />
                        }
                        link={`/a-propos`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__pObrt
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___49Jcg
                          )}
                        >
                          {"Une Marque Engag\u00e9e"}
                        </div>
                      </Button2>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__iExyy
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__xDOqM
                            )}
                            role={"img"}
                          />
                        }
                        link={`/catalogue`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__anzFl
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__cDjYy
                          )}
                        >
                          {"Catalogue"}
                        </div>
                      </Button2>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__rwx1O
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__fi14A
                            )}
                            role={"img"}
                          />
                        }
                        link={`/faq`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg___7A7Ej
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__ja3Kd
                          )}
                        >
                          {"FAQ"}
                        </div>
                      </Button2>
                    </Stack__>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__yVjTy)}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__y66H)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__xdRu
                        )}
                      >
                        {"MENTIONS G\u00c9N\u00c9RALES"}
                      </div>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__tyKSi
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__ayLjo
                            )}
                            role={"img"}
                          />
                        }
                        link={`/moyens-de-paiement`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg___885Ls
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__sfaZr
                          )}
                        >
                          {"Moyens de Paiement"}
                        </div>
                      </Button2>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2___2BG7R
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__wfez7
                            )}
                            role={"img"}
                          />
                        }
                        link={`/livraisons-et-retours`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__p8Mdm
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__tjVjV
                          )}
                        >
                          {"Livraisons & Retours"}
                        </div>
                      </Button2>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__saK43
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg___92GkB
                            )}
                            role={"img"}
                          />
                        }
                        link={`/contact`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__yugO
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__p5HaO
                          )}
                        >
                          {"Contact"}
                        </div>
                      </Button2>
                    </Stack__>
                  </div>
                  <div
                    className={classNames(projectcss.all, sty.column__mvOjg)}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__vUfMt)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__sGzpx
                        )}
                      >
                        {"INFORMATIONS L\u00c9GALES"}
                      </div>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2___4Sipo
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__m6JoC
                            )}
                            role={"img"}
                          />
                        }
                        link={`/conditions-generales-de-vente`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__si9OM
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__fozbR
                          )}
                        >
                          {"Conditions G\u00e9n\u00e9rales de Vente"}
                        </div>
                      </Button2>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__knUpF
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__troi4
                            )}
                            role={"img"}
                          />
                        }
                        link={`/politique-de-confidentialite`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__cR8Nl
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___4VyNt
                          )}
                        >
                          {"Politique de Confidentialit\u00e9"}
                        </div>
                      </Button2>
                      <Button2
                        className={classNames(
                          "__wab_instance",
                          sty.button2__blESh
                        )}
                        color={"link"}
                        endIcon={
                          <Icon38Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__we9La
                            )}
                            role={"img"}
                          />
                        }
                        link={`/mentions-legales`}
                        size={"minimal"}
                        startIcon={
                          <CheckSvgIcon
                            className={classNames(
                              projectcss.all,
                              sty.svg__meNRz
                            )}
                            role={"img"}
                          />
                        }
                        submitsForm={true}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__eu1V7
                          )}
                        >
                          {"Mentions L\u00e9gales"}
                        </div>
                      </Button2>
                    </Stack__>
                  </div>
                </Stack__>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__gd4Hy
                  )}
                >
                  <React.Fragment>
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                      style={{ fontWeight: 400 }}
                    >
                      {"\u00a9 2025 Cloven, Tous droits r\u00e9serv\u00e9s."}
                    </span>
                  </React.Fragment>
                </div>
              </div>
            </section>
          ) : null}
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  contact: ["contact", "navigationBar", "h1", "embedHtml"],
  navigationBar: ["navigationBar"],
  h1: ["h1"],
  embedHtml: ["embedHtml"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  contact: "div";
  navigationBar: typeof NavigationBar;
  h1: "h1";
  embedHtml: typeof Embed;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicContact__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicContact__VariantsArgs;
    args?: PlasmicContact__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicContact__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicContact__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicContact__ArgProps,
          internalVariantPropNames: PlasmicContact__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicContact__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "contact") {
    func.displayName = "PlasmicContact";
  } else {
    func.displayName = `PlasmicContact.${nodeName}`;
  }
  return func;
}

export const PlasmicContact = Object.assign(
  // Top-level PlasmicContact renders the root element
  makeNodeComponent("contact"),
  {
    // Helper components rendering sub-elements
    navigationBar: makeNodeComponent("navigationBar"),
    h1: makeNodeComponent("h1"),
    embedHtml: makeNodeComponent("embedHtml"),

    // Metadata about props expected for PlasmicContact
    internalVariantProps: PlasmicContact__VariantProps,
    internalArgProps: PlasmicContact__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Contact",
      description:
        "Une question ? Contactez-nous directement du lundi au vendredi de 9h à 18h par téléphone, par e-mail ou ou via notre formulaire de contact.\n",
      ogImageSrc:
        "https://site-assets.plasmic.app/be080d9b95ba4f9295d20e3bd224220e.png",
      canonical: ""
    }
  }
);

export default PlasmicContact;
/* prettier-ignore-end */
